#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. /etc/os-release

if [ "${ID}" == "altlinux" ]; then
    git clone https://github.com/arenadata/gp-xerces
    cd gp-xerces
    mkdir build
    cd build
    ../configure --prefix=$1
    make
    make install DESTDIR=$2
    export LD_LIBRARY_PATH=$2$1/lib:$LD_LIBRARY_PATH
    OPTS="--with-includes=$2$1/include --with-libraries=$2$1/lib"
    cd ../..
fi

export BUILDNUMBER="${3}-${4}"
./configure --enable-gpperfmon \
            --enable-orca \
            --with-python \
            --with-gssapi \
            --with-krb5 \
            --with-ldap \
            --with-openssl \
            --with-libxml \
            --with-libxslt \
            --with-zstd \
            --enable-debug \
            --enable-ic-proxy \
            --prefix=$1 $OPTS --with-python --with-perl
